const MESSAGES = {
  SUCCESS: "SUCCESS",

  // USER
  USER_CREATE_SUCCESS: "USER.CREATE.SUCCESS",
  USER_INDEX_SUCCESS: "USER.INDEX.SUCCESS",
  USER_GET_SUCCESS: "USER.GET.SUCCESS",
  USER_COURSE_GET_SUCCESS: "USER.COURSE.GET.SUCCESS",
  USER_ACADEMIC_INFO_GET_SUCCESS: "USER.ACADEMIC.INFO.GET.SUCCESS",
  USER_DEPARTMENT_GET_SUCCESS: "USER.DEPARTMENT.GET.SUCCESS",
  USER_UPDATE_SUCCESS: "USER.UPDATE.SUCCESS",
  USER_TRANSCRIPT_GET_SUCCESS: "USER.TRANSCRIPT.GET.SUCCESS",
  
  // STUDENT
  STUDENT_ACADEMIC_INFO_UPDATE_SUCCESS: "STUDENT.ACADEMIC_INFO.UPDATE.SUCCESS",
  STUDENT_ACADEMIC_INFO_DELETE_SUCCESS: "STUDENT.ACADEMIC_INFO.DELETE.SUCCESS",
  STUDENT_COURSE_SELECTION_SUCCESS: "STUDENT.COURSE_SELECTION.SUCCESS",
  STUDENT_COURSE_SELECTION_UPDATE_STATUS_SUCCESS: "STUDENT.COURSE_SELECTION.UPDATE_STATUS.SUCCESS",
  STUDENT_WEEKLY_SCHEDULE_GET_SUCCESS: "STUDENT.WEEKLY_SCHEDULE.GET.SUCCESS",
  STUDENT_EXAMS_GET_SUCCESS: "STUDENT.EXAMS.GET.SUCCESS",

  // TEACHER
  TEACHER_COURSE_GET_SUCCESS: "TEACHER.COURSE.GET.SUCCESS",
  TEACHER_EXAMS_GET_SUCCESS: "TEACHER.EXAMS.GET.SUCCESS",

  // EXAM
  EXAM_CREATE_SUCCESS: "EXAM.CREATE.SUCCESS",
  EXAM_UPDATE_SUCCESS: "EXAM.UPDATE.SUCCESS",
  EXAM_DELETE_SUCCESS: "EXAM.DELETE.SUCCESS",

  // FACULTY
  FACULTY_CREATE_SUCCESS: "FACULTY.CREATE.SUCCESS",
  FACULTY_INDEX_SUCCESS: "FACULTY.INDEX.SUCCESS",
  FACULTY_GET_SUCCESS: "FACULTY.GET.SUCCESS",
  FACULTY_UPDATE_SUCCESS: "FACULTY.UPDATE.SUCCESS",
  FACULTY_DEPARTMENT_INDEX_SUCCESS: "FACULTY.DEPARTMENT.INDEX.SUCCESS",

  // DEPARTMENT
  DEPARTMENT_CREATE_SUCCESS: "DEPARTMENT.CREATE.SUCCESS",
  DEPARTMENT_INDEX_SUCCESS: "DEPARTMENT.INDEX.SUCCESS",
  DEPARTMENT_GET_SUCCESS: "DEPARTMENT.GET.SUCCESS",
  DEPARTMENT_UPDATE_SUCCESS: "DEPARTMENT.UPDATE.SUCCESS",
  DEPARTMENT_COURSE_INDEX_SUCCESS: "DEPARTMENT.COURSE.INDEX.SUCCESS",
  DEPARTMENT_OPENED_COURSE_INDEX_SUCCESS: "DEPARTMENT.OPENED_COURSE.INDEX.SUCCESS",
  DEPARTMENT_TEACHER_INDEX_SUCCESS: "DEPARTMENT.TEACHER.INDEX.SUCCESS",
  DEPARTMENT_STUDENT_INDEX_SUCCESS: "DEPARTMENT.STUDENT.INDEX.SUCCESS",
  DEPARTMENT_EXAMS_GET_SUCCESS: "DEPARTMENT.EXAMS.GET.SUCCESS",

  // COURSE
  COURSE_CREATE_SUCCESS: "COURSE.CREATE.SUCCESS",
  COURSE_UPDATE_SUCCESS: "COURSE.UPDATE.SUCCESS",
  COURSE_GET_SUCCESS: "COURSE.GET.SUCCESS",
  COURSE_UPDATE_SUCCESS: "COURSE.UPDATE.SUCCESS",

  // OPENED COURSE
  OPENED_COURSE_CREATE_SUCCESS: "OPENED_COURSE.CREATE.SUCCESS",
  OPENED_COURSE_UPDATE_SUCCESS: "OPENED_COURSE.UPDATE.SUCCESS",
  OPENED_COURSE_GET_SUCCESS: "OPENED_COURSE.GET.SUCCESS",
  OPENED_COURSE_STUDENTS_GET_SUCCESS: "OPENED_COURSE.STUDENTS.GET.SUCCESS",

  // POST
  POST_CREATE_SUCCESS: "POST.CREATE.SUCCESS",
  POST_GET_SUCCESS   : "POST.GET.SUCCESS",
  POST_UPDATE_SUCCESS: "POST.UPDATE.SUCCESS",
};

module.exports = {
  MESSAGES,
};
