export const URL = {
    HOME: '/home',
    DEFAULT_PATH: '/',
    LOGIN: '/login',
    REGISTER: '/register',
    EXAMS: '/exams',
    USER: '/user',
    USERS: '/users',
    COURSE: '/course',
    GIVEN: '/given',
    OPENED_COURSE: '/opened-course',
    COURSES: '/courses',
    FACULTIES: '/faculties',
    DEPARTMENTS: '/departments',
    SELECTION: '/selection',
    TEACHER: '/teacher',
    STUDENT: '/student',
    TRANSCRIPT: '/transcript',
    WEEKLY_SCHEDULE: '/weekly-schedule',
    REVIEW_SELECTIONS: '/review-selections',
    MENTORED_STUDENTS: '/mentored-students',
};
